name: Build and Upload Executable

on:
  push:
    tags:
      - 'v*' # Trigger this workflow when a tag is pushed (e.g., v1.0.0)
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build executable
        run: |
          pip install pyinstaller
          pyinstaller --onefile --add-data "resources:resources" src/main.py

      - name: Rename executables
        shell: bash
        run: |
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            mv dist/main dist/ai-git-tools-linux
          elif [ "${{ matrix.os }}" = "macos-latest" ]; then
            mv dist/main dist/ai-git-tools-macos
          elif [ "${{ matrix.os }}" = "windows-latest" ]; then
            mv dist/main.exe dist/ai-git-tools-win.exe
          fi

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          make_latest: true
          draft: false
          prerelease: false
          files: |
            dist/ai-git-tools-linux
            dist/ai-git-tools-macos
            dist/ai-git-tools-win.exe