name: Build and Upload Executable

on:
  push:
    tags:
      - 'v*' # Trigger this workflow when a tag is pushed (e.g., v1.0.0)
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python (if your CLI is Python-based)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run Makefile build
      - name: Build executable
        run: |
          make build

      # Upload to GitHub Releases
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/ai-git-tools
          asset_name: ai-git-tools
          asset_content_type: application/octet-stream