name: Tests and Coverage

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt
          pip install coveralls

      - name: Run Tests and Coverage
        run: |
          pytest --cov=src --cov-report=xml --cov-fail-under=93

      - name: Upload coverage to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          coverage run --source=src -m pytest tests/
          coverage report --fail-under=85
          coveralls

      - name: Upload Coverage Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/